### ISSUE TITLE
Implement logging for Fleepbot frontend

### ISSUE THREAD

**Issue by aleemet** [WaldurChatbot/FleepBot#5]
- [x] - Logs should be configurable from a config file, preferably .ini as we are already using a .ini file for general configuration.
- [x] - External imported modules logging should be disabled or if possible integrated with our logging.
- [x] - Log line should have a level, timestamp, script name, content and maybe thread name.
- [x] - Standard level should be Info

**Comment by aleemet** [comment]
Continuation of https://github.com/WaldurChatbot/Waldur-Chatbot/issues/16

**Comment by m2rtk** [comment]
Done in 2c8d694879168569fefe5c101e9adccde41f457f
